# NAME: SAGAR SURYAKANT DHURI
# TASK NO 4: PREDICTION USING DECISION TREE ALGORITHM

# Importing Libraries

In [53]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split 
from sklearn import metrics 

# Importing URL

In [38]:
iris=pd.read_csv('C:/Users/Admin/OneDrive/Desktop/intern Task4/Iris.csv')


# Displaying Dataset

In [39]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [55]:
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [40]:
X=iris.drop(['Species','SepalWidthCm'],axis=1) 
Y=iris['Species']

# Train Test Split

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=0)


In [42]:
from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

# Decision Tree

In [43]:
from sklearn.tree import DecisionTreeClassifier 

In [44]:
dtree=DecisionTreeClassifier()

In [45]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

# Predictions

In [46]:
print(X_test)
predictions=dtree.predict(X_test)
predictions

      Id  SepalLengthCm  PetalLengthCm  PetalWidthCm
50    51            7.0            4.7           1.4
4      5            5.0            1.4           0.2
74    75            6.4            4.3           1.3
132  133            6.4            5.6           2.2
76    77            6.8            4.8           1.4
61    62            5.9            4.2           1.5
0      1            5.1            1.4           0.2
108  109            6.7            5.8           1.8
56    57            6.3            4.7           1.6
37    38            4.9            1.5           0.1
127  128            6.1            4.9           1.8
82    83            5.8            3.9           1.2
54    55            6.5            4.6           1.5
140  141            6.7            5.6           2.4
144  145            6.7            5.7           2.5
141  142            6.9            5.1           2.3
52    53            6.9            4.9           1.5
21    22            5.1            1.5        

array(['Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor'], dtype=object)

In [47]:
from sklearn.metrics import classification_report,confusion_matrix

In [48]:
print(classification_report(y_test,predictions))

                 precision    recall  f1-score   support

    Iris-setosa       0.92      1.00      0.96        11
Iris-versicolor       1.00      0.91      0.95        11
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



In [49]:
print(confusion_matrix(y_test,predictions))

[[11  0  0]
 [ 1 10  0]
 [ 0  0  8]]


In [65]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

# Predicting Iris Species

In [66]:
x_new = np.array([[5.1, 3.5, 1.4, 0.2]])
prediction = knn.predict(x_new)
print("Prediction: {}".format(prediction))

Prediction: ['Iris-setosa']


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [69]:
# Thank You